import { IndividualDetailsType } from "../context/DashboardContext";
export const DefaultIndividual: IndividualDetailsType = {
    _id: "",
    email: "",
    fullName: "",
    avatar: "",
    adhaarNo: "",
    dateOfBirth: "",
    permanentAddress: {
        street: "",
        city: "",
        state: "",
        pincode: 0,
        _id: "",
    },
    presentAddress: {
        street: "",
        city: "",
        state: "",
        pincode: 0,
        _id: "",
    },
    phoneNo: "",
    password: "",
    receivedAlerts: [],
    bloodReports: [],
    eventsRegistered: [],
    eventsAttended: [],
    createdAt: "",
    updatedAt: "",
    __v: 0,
    refreshToken: "",
    currentLocation: {
        latitude: 0,
        longitude: 0,
    },
};
